# Generated by Django 4.2.1 on 2023-06-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_suno_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userId',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='sign_suno_backend.user'),
        ),
    ]
