import Head from "next/head";
import {
  Box,
  Center,
  Flex,
  Heading,
  HStack,
  Link,
  VStack,
} from "@chakra-ui/layout";
import Navbar from "@/components/Navbarss-front";
//const inter = Inter({ subsets: ["latin"] });
import { Image } from "@chakra-ui/react";
import { Button, ButtonGroup } from "@chakra-ui/react";
import { Text } from "@chakra-ui/react";
import { Grid, GridItem } from "@chakra-ui/react";
import { Circle } from "@chakra-ui/layout";
// import React, { useState, useRef } from "react";
import { Switch } from '@chakra-ui/react';

import React, { useEffect, useRef, useState } from "react";

export default function Home() {
  function sendData() {}

  const [isCapturing, setIsCapturing] = useState(false);
  const videoRef = useRef(null);

  useEffect(() => {
    navigator.mediaDevices
      .getUserMedia({ video: true })
      .then((stream) => {
        videoRef.current.srcObject = stream;
      })
      .catch((error) => {
        console.error("Error accessing camera", error);
      });
  }, []);

  const handleStartCapture = () => {
    setIsCapturing(true);
    videoRef.current.play();
  };

  const handleStopCapture = () => {
    setIsCapturing(false);
    videoRef.current.pause();
  };

  /*for toggle button*/
  const [isChecked, setIsChecked] = useState(false);

  const handleToggleChange = () => {
    setIsChecked(!isChecked);
  };

  return (
    <>
      <main style={{ height: "100vh"}}>
        <Head>
          <title>Sign Suno</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="assets/icons/Hand_logo_yellow_1.svg" />
        </Head>

        <Flex minHeight="100vh">
          <Box
            // height="100vh"
            // width="100%"
            bgGradient="linear(to-r, #0B51DA, #4878FF)"
          >
            <Navbar />
            <Grid
              templateColumns="repeat(2, 1fr)"
              gap={20}
              
            >
              <GridItem
                w="100%"
              >
                {/* <Center>
                  <Box boxSize={"lg"} height="100%">
                    <VStack>
                      <video
                        ref={videoRef}
                        autoPlay
                        muted
                        // playsInline
                      />
                      {!isCapturing && (
                        <Button
                          fontSize={"md"}
                          fontWeight={600}
                          color={"#0B51DA"}
                          fontFamily="Inter"
                          size="sm"
                          bg={"white"}
                          href={"/"}
                          _hover={{
                            bg: "#FFD53F",
                          }}
                          onClick={handleStartCapture}
                        >
                          Start Capture
                        </Button>
                      )}
                      {isCapturing && (
                        <Button
                          fontSize={"md"}
                          fontWeight={600}
                          color={"#0B51DA"}
                          fontFamily="Inter"
                          size="sm"
                          bg={"white"}
                          href={"/"}
                          _hover={{
                            bg: "#FFD53F",
                          }}
                          onClick={handleStopCapture}
                        >
                          Stop Capture
                        </Button>
                      )}
                     
                    </VStack>
                  </Box>
                </Center> */}
                <Center>
                  <Box display="flex" alignItems="center" justifyContent="center"  >
                      <VStack>
                        <video
                          ref={videoRef}
                          autoPlay
                          muted
                          height={"100vh"}
                          style={{ width: "100%", height: "100%" }}
                        
                        />
                         {!isCapturing && (
                            <Button
                              zIndex={10}
                              fontSize={"md"}
                              fontWeight={600}
                              color={"#0B51DA"}
                              fontFamily="Inter"
                              size="sm"
                              bg={"white"}
                              href={"/"}
                              _hover={{
                                bg: "#FFD53F",
                              }}
                              onClick={handleStartCapture}
                            >
                              Start Capture
                            </Button>
                          )}
                          {isCapturing && (
                            <Button
                              fontSize={"md"}
                              fontWeight={600}
                              color={"#0B51DA"}
                              fontFamily="Inter"
                              size="sm"
                              bg={"white"}
                              href={"/"}
                              _hover={{
                                bg: "#FFD53F",
                              }}
                              onClick={handleStopCapture}
                            >
                              Stop Capture
                            </Button>
                          )}
                      </VStack>
                  </Box>
                 
                </Center>

              </GridItem>
              <GridItem
                display={"flex"}
                flexFlow={"column"}
                marginTop="10"
                w="100%"
              >
                <VStack gap={8} alignItems={"initial"}>
                <Box >
                  <Box
                    sx={{
                      position: 'absolute',
                      display: 'inline-block',
                      width: '24',
                      height: '8',
                      borderRadius: 'full',
                      borderWidth: '2px',
                      top:"-5",
                      borderColor: 'yellow.400',
                      _before: {
                        content: '""',
                        position: 'absolute',
                        width: '6',
                        height: '6',
                        top: '50%',
                        transform: 'translateY(-50%)',
                        borderRadius: 'full',
                        bg: 'yellow.400',
                        transition: 'transform 0.3s',
                        transform: isChecked ? 'translateX(67px) translateY(-50%)' : 'translateX(1px) translateY(-50%)',
                      },
                    }}
                    onClick={handleToggleChange}
                  >
                    <Box
                      position="absolute"
                      top="50%"
                      transform="translate(-50%, -50%)"
                      left={isChecked ? '8' : '14'}
                      fontSize="xs"
                      fontWeight="bold"
                      color={isChecked ? 'yellow.400' : 'yellow.400'}
                    >
                      {isChecked ? 'American' : 'Indian'}
                    </Box>
                    <Switch
                      size="sm"
                      isChecked={isChecked}
                      onChange={handleToggleChange}
                      display="none"
                    />
                  </Box>
                </Box>
                  <HStack spacing={10}>
                    {/* <Button
                        
                        _hover={{
                          bg: '#FFD53F',
                        }}
                        // w={32}
                        // height={20}
                        boxSize={16}
                        borderRadius="100%"
                        color='#FFFFFF'
                        marginLeft={5}> */}
                    <Image
                      //  boxSize={24}
                      size={"100%"}
                      boxSize={16}
                      
                      src="assets/icons/audio.svg"
                    />

                    {/* </Button> */}
                    <Text
                      color="#FFFFFF"
                      Font="Inter"
                      fontWeight="600"
                      fontSize="20"
                    >
                      blah blah
                    </Text>
                  </HStack>
                  <HStack>
                    <Button
                      fontSize={"md"}
                      fontWeight={600}
                      color={"White"}
                      fontFamily="Inter"
                      bg={"none"}
                      size="sm"
                      border={"1px solid #F6F9FF"}
                      href={"/"}
                      _hover={{
                        opacity: 0.7,
                      }}
                    >
                      Save Phrases
                    </Button>
                    <Button
                      fontSize={"md"}
                      fontWeight={600}
                      color={"#0B51DA"}
                      fontFamily="Inter"
                      size="sm"
                      bg={"white"}
                      href={"/"}
                      _hover={{
                        bg: "#FFD53F",
                      }}
                    >
                      Reply
                    </Button>
                  </HStack>            
                  <VStack alignItems={"initial"}>
                    <Text
                      fontWeight="400"
                      color="#FFFFFF"
                      fontSize="20"
                      Font="Inter"
                    >
                      Communicate Using:
                    </Text>
                    <HStack>
                      <Link href="">
                        <Button
                          _hover={{
                            bg: "#FFD53F",
                          }}
                          boxSize="12"
                          borderRadius="50%"
                          color="#FFFFFF"
                        >
                          <Image size="100%" src="assets/icons/camera.svg" />
                        </Button>
                      </Link>
                      <Link href="/home_type">
                        <Button
                          _hover={{
                            bg: "#FFD53F",
                          }}
                          boxSize="12"
                          borderRadius="50%"
                          color="#FFFFFF"
                        >
                          <Image size="100%" src="assets/icons/type.svg" />
                        </Button>
                      </Link>
                    </HStack>
                  </VStack>
                </VStack>
              </GridItem>
            </Grid>
          </Box>
        </Flex>
      </main>
    </>
  );
}
