import Head from "next/head";
import React from "react";
import { Inter } from "@next/font/google";
import {
  Box,
  Center,
  Flex,
  Heading,
  HStack,
  Link,
  VStack,
} from "@chakra-ui/layout";
import { Checkbox, color, Text } from "@chakra-ui/react";
import { Button } from "@chakra-ui/button";
import { FormControl } from "@chakra-ui/form-control";
import { Input, InputRightElement, InputGroup } from "@chakra-ui/input";
import { ViewIcon, ViewOffIcon } from "@chakra-ui/icons";
import { useState } from "react";
import axios from "axios";
import { Router } from "react-router-dom";
import { useBreakpointValue } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [email_id, setEmail] = useState("");
  const [userId, setUserId] = useState("");

  const formControlWidth = useBreakpointValue({ base: "100%", md: "md" });

  const sendData = async (event) => {
    event.preventDefault();

    localStorage.setItem("username", userId);
    localStorage.setItem("email", email_id);
    //let responseData;
    try {
      axios
        .post("http://127.0.0.1:8000/api/pass_reset_details", {
          username: userId,
        })
        .then((response) => {
          console.log("response", response.data["status"]);

          if (response.data["status"] == 200) {
            window.location.href = "/otp_pass";
          }
        })
        .catch(console.log);
    } catch (error) {
      console.log(error);
    }
  };

  function handleEmailChange(event) {
    setEmail(event.target.value);
  }

  function handleUserChange(event) {
    setUserId(event.target.value);
  }

  const [bgHeight, setBgHeight] = React.useState("100vh");

  function handleBgLoad(event) {
    const height = `${event.target.height}px`;
    setBgHeight(height);
  }

  const style = React.useMemo(
    () => ({ height: `${bgHeight} !important` }),
    [bgHeight]
  );

  return (
    <>
      <Head>
        <title>Sign Suno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/icons/Hand_logo_yellow_1.svg" />
      </Head>
      <main style={{ height: "100vh" }}>
        <Flex onLoad={handleBgLoad} sx={{ "&": { style } }}>
          <Box
            flex="1"
            backgroundSize="cover"
            bgImage="url('assets/images/Carousel2.svg')"
            bgPosition="center"
            bgRepeat="no-repeat"
            minH={"100vh"}
            display={{ base: "none", lg: "block" }}
          >
            <Center>
              <VStack>
                <Text
                  color="white"
                  font="Inter"
                  fontWeight="800"
                  fontSize="28px"
                  align="center"
                  marginTop="10%"
                >
                  Communicate to rise on <br />
                  the leaderboard
                </Text>

                <Text
                  color="white"
                  Font="Inter"
                  FontWeight="400"
                  FontSize="18px"
                  align="center"
                >
                  The more you communicate through us, the <br />
                  higher you score!
                </Text>
              </VStack>
            </Center>
          </Box>
          <Box flex="1"  height="100%"  display={{ base: "block", lg:"auto"}}>
            <Flex alignItems="center" justifyContent="center" minHeight="100vh">
              <Box width="100%" height="100%" >
                <Center marginBottom="6" flexDirection="column">
                  <Heading fontSize="3xl" color="#0B51DA">
                    Sign
                  </Heading>
                  <Heading fontSize="3xl" color="#0B51DA">
                    सुनो
                  </Heading>
                  <Text
                    marginTop="2%"
                    font="Inter"
                    fontWeight="600"
                    fontSize="28px"
                  >
                    Let's Reset Your Password
                  </Text>
                </Center>

                <Center>
                  <VStack width="100%">
                    <form
                      onSubmit={sendData}
                    >
                      <VStack gap={4} width={formControlWidth}>
                        <FormControl>
                          <Input
                            backgroundColor="#E2EAF8"
                            type="text"
                            placeholder="Username"
                            value={userId}
                            onChange={handleUserChange}
                            required
                          />
                        </FormControl>
                        <FormControl>
                          <Input
                            backgroundColor="#E2EAF8"
                            type="email"
                            placeholder="Email"
                            value={email_id}
                            onChange={handleEmailChange}
                            required
                          />
                        </FormControl>
                        <Button
                          backgroundColor="#0B51DA"
                          color="white"                        
                          type="submit"
                          width={formControlWidth}
                        >
                          Continue
                        </Button>
                      </VStack>
                    </form>
                  </VStack>
                </Center>
              </Box>
            </Flex>
          </Box>
        </Flex>
      </main>
    </>
  );
}
