import Head from "next/head";
import {
  Box,
  Center,
  Flex,
  Stack,
  Heading,
  HStack,
  Link,
  VStack,
} from "@chakra-ui/layout";
import Navbar from "@/components/Navbarss-front";
//const inter = Inter({ subsets: ["latin"] });
import { Image } from "@chakra-ui/react";
import { Button, ButtonGroup } from "@chakra-ui/react";
import { Text } from "@chakra-ui/react";
import { Grid, GridItem } from "@chakra-ui/react";
import { useMediaQuery } from "@chakra-ui/react";
import "@fontsource/londrina-solid";
import "@fontsource/inter";

export default function Home() {
  function sendData() {}

  /*To check if its mobile screen */
  const [isMobile] = useMediaQuery("(max-width: 768px)"); // Returns true on mobile, false on desktop

  if (isMobile) {
    return (
      <>
        <main style={{ maxHeight: "100vh" }}>
          <Head>
            <title>Speak</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="assets/icons/Hand_logo_yellow_1.svg" />
          </Head>
          <Flex height="100vh" flexDirection="column">
            <Box flexGrow={1} width="100%" bgColor={"#0359C8"}>
              <Navbar />
              <Box
                align="center"
                justify="center"
                // padding={5}
              >
                <Image
                  boxSize="3xs"
                  // height={56}
                  marginBottom={-40}
                  // width="570px"
                  // height="120px"
                  src="assets/text/Choose your option.svg"
                />
              </Box>
              <VStack gap={5} align="center" justify="center" height="100vh">
                <Box>
                  <VStack>
                    <Link href="/home_sign">
                      <Button
                        _hover={{
                          bg: "#FFD53F",
                        }}
                        boxSize="20"
                        borderRadius="50%"
                        color="#FFFFFF"
                      >
                        <Image boxSize={10} src="assets/icons/camera.svg" />
                      </Button>
                    </Link>
                    <Text
                      fontFamily="londrina solid"
                      fontWeight="400"
                      color="#FFFFFF"
                      fontSize="20px"
                    >
                      Sign
                    </Text>
                  </VStack>
                </Box>

                <VStack>
                  <Link href="/home_speak">
                    <Button
                      _hover={{
                        bg: "#FFD53F",
                      }}
                      boxSize="20"
                      borderRadius="50%"
                      color="#FFFFFF"
                    >
                      <Image boxSize={10} src="assets/icons/microphone.svg" />
                    </Button>
                  </Link>
                  <Text
                    fontFamily="Londrina Solid"
                    fontWeight="400"
                    color="#FFFFFF"
                    fontSize="20px"
                  >
                    Speak
                  </Text>
                </VStack>

                <VStack>
                  <Link href="/home_type">
                    <Button
                      _hover={{
                        bg: "#FFD53F",
                      }}
                      boxSize="20"
                      borderRadius="50%"
                      color="#FFFFFF"
                    >
                      <Image boxSize={10} src="assets/icons/type.svg" />
                    </Button>
                  </Link>
                  <Text
                    fontFamily="Londrina Solid"
                    fontWeight="400"
                    color="#FFFFFF"
                    fontSize="20"
                  >
                    Text
                  </Text>
                </VStack>
              </VStack>
            </Box>
          </Flex>
        </main>
      </>
    );
  }

  return (
    <>
      <main style={{ height: "100vh" }}>
        <Head>
          <title>Sign Suno</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="assets/icons/Hand_logo_yellow_1.svg" />
        </Head>

        <Flex height="100%">
          <Box
            height="100%"
            width="100%"
            bgGradient="linear(to-r, #0B51DA, #4878FF)"
          >
            <Box
              style={{ zIndex: 100 }}
              //   style={{
              //     position: "fixed",
              //     top: 0,
              //     left: 0,
              //     z-index: "100",
              //     width: "100%"
              // }}
            >
              <Navbar />
            </Box>

            <Center>
              <VStack>
                <Box
                  marginTop={10}
                  // width="605px"
                  // height="156px"
                >
                  <Image
                    boxSize="2xl"
                    height={52}
                    // width="570px"
                    // height="120px"
                    src="assets/text/Choose your option2.svg"
                  />
                </Box>

                <Grid templateColumns="repeat(3, 1fr)" gap={96}>
                  <GridItem colSpan={1}>
                    <VStack>
                      <Link href="/home_sign">
                        <Button
                          _hover={{
                            bg: "#FFD53F",
                          }}
                          boxSize="24"
                          borderRadius="50%"
                          color="#FFFFFF"
                        >
                          <Image
                            boxSize="12"
                            // width="36"
                            // height="36"
                            src="assets/icons/camera.svg"
                          />
                        </Button>
                      </Link>
                      <Text
                        fontFamily={"londrina solid"}
                        fontWeight="400"
                        color="#FFFFFF"
                        fontSize="24px"
                      >
                        Sign
                      </Text>
                    </VStack>
                  </GridItem>
                  <GridItem colSpan={1}>
                    <VStack>
                      <Link href="/home_speak">
                        <Button
                          _hover={{
                            bg: "#FFD53F",
                          }}
                          boxSize="24"
                          borderRadius="50%"
                          color="#FFFFFF"
                          zIndex={1}
                        >
                          <Image
                            boxSize="12"
                            src="assets/icons/microphone.svg"
                          />
                        </Button>
                      </Link>
                      <Text
                        fontFamily={"londrina solid"}
                        fontWeight="400"
                        color="#FFFFFF"
                        fontSize="24px"
                      >
                        Speak
                      </Text>
                    </VStack>
                  </GridItem>
                  <GridItem colSpan={1}>
                    <VStack>
                      <Link href="/home_type">
                        <Button
                          _hover={{
                            bg: "#FFD53F",
                          }}
                          boxSize="24"
                          borderRadius="50%"
                          color="#FFFFFF"
                        >
                          <Image boxSize="12" src="assets/icons/type.svg" />
                        </Button>
                      </Link>
                      <Text
                        fontFamily={"londrina solid"}
                        fontWeight="400"
                        color="#FFFFFF"
                        fontSize="24"
                      >
                        Text
                      </Text>
                    </VStack>
                  </GridItem>
                  {/* </HStack> */}
                </Grid>
              </VStack>
            </Center>
          </Box>
        </Flex>
      </main>
    </>
  );
}
