import { Avatar, Img, keyframes } from "@chakra-ui/react";
import { IconButton } from "@chakra-ui/react";
import { Icon, leftIcon, BiLike, BiChat, BiShare } from "@chakra-ui/react";
import Head from "next/head";
import { Box, Center, Flex, Heading, VStack } from "@chakra-ui/layout";
import Navbar from "@/components/Navbarss-front";
//const inter = Inter({ subsets: ["latin"] });
import { Image } from "@chakra-ui/react";
import { Button, ButtonGroup } from "@chakra-ui/react";
import { Text } from "@chakra-ui/react";
import { Grid, GridItem } from "@chakra-ui/react";

import { FormControl } from "@chakra-ui/react";
import { Input } from "@chakra-ui/react";
import { Card, CardHeader, CardBody, CardFooter } from "@chakra-ui/react";
import React, { useState, useEffect, useLayoutEffect } from "react";
import { useMediaQuery } from "@chakra-ui/react";

import {
  List,
  ListItem,
  ListIcon,
  OrderedList,
  UnorderedList,
} from "@chakra-ui/react";

import axios from "axios";
import "@fontsource/londrina-solid";

export default function leaderboard() {
  const [user, setUser] = useState("");
  const [list, setList] = useState([]);
  const [current, setCurrent] = useState({});

  useLayoutEffect(() => {
    const userId = localStorage.getItem("user");
    setUser(userId);

    axios
      .post("http://127.0.0.1:8000/api/current_user", {
        username: userId,
      })
      .then((response) => {
        const xyz = response.data;
        console.log("***current user: ", xyz);
        setCurrent(xyz);
      })
      .catch(console.log);

    axios
      .get("http://127.0.0.1:8000/api/leaderboard_users")
      .then((response) => {
        console.log(response.data);
        const xyz = response.data;
        setList(xyz);
      })
      .catch(console.log);
  }, []);

  console.log("Users: ", list);
  console.log("current: ", current);

  function sendData() {}

  // const [cards, setCards] = useState([]);
  const cards = [];
  let rank;
  for (let i = 0; i < list.length; i++) {
    cards.push({
      title: `${i + 1}`,
    });
    if (list[i]["username"] == current["username"]) {
      rank = i + 1;
    }
  }

  const [isMobile] = useMediaQuery("(max-width: 768px)"); // Returns true on mobile, false on desktop

  if (isMobile) {
    return (
      <>
        <main style={{ maxHeight: "100vh" }}>
          <Head>
            <title>Sign Suno</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="assets/icons/Hand_logo_yellow_1.svg" />
          </Head>
          <Flex height="100vh" flexDirection="column">
            <Box flexGrow={1} width="100%" bgColor={"#0359C8"}>
              <Navbar />

              <Grid
                marginTop={10}
                padding={2}
                templateColumns="repeat(1, 1fr)"
                gap={6}
                width={"100%"}
              >
                <GridItem
                  display={"flex"}
                  flexDirection={"column"}
                  justify="center"
                  w="100%"
                >
                  <Center>
                    <Card
                      height={36}
                      bgColor={"rgba(22, 75, 179, 0.6)"}
                      width={"100%"}
                    >
                      <CardHeader className="card">
                        <Flex spacing="2">
                          <Flex flex={1} gap={10} alignItems="center" flexWrap="wrap">
                            <VStack color={"white"}>
                              <Avatar
                                name={current["name"]}
                                src={`http://localhost:8000${current["profile"]}`}
                              />
                              <Box>
                                <Heading size="sm">{current["name"]}</Heading>
                                <Text>{current["username"]}</Text>
                              </Box>
                            </VStack>
                            <VStack ml={"auto"}>
                              <Text color={"white"}>#Rank</Text>
                              <Box
                                color={"#FFD53F"}
                                fontFamily="Londrina Solid"
                              >
                                <Heading size="md">{rank}</Heading>
                              </Box>
                            </VStack>
                            <VStack ml="auto">  
                              <Text color={"white"}>#xps</Text>
                              <Box
                                color={"#FFD53F"}
                                fontFamily="Londrina Solid"
                                
                              >
                                <Heading size="md">
                                  {current["score"]} XP
                                </Heading>
                              </Box>
                            </VStack>
                          </Flex>
                        </Flex>
                      </CardHeader>
                    </Card>
                  </Center>
                </GridItem>
                <Text
                  fontFamily="londrina solid"
                  fontStyle="normal"
                  fontWeight={400}
                  fontSize={24}
                  color="#FFFFFF"
                  marginTop={5}
                >
                  Leaderboard
                </Text>
                <GridItem w="100%" id="myCardsContainer">
                  {/* <Center > */}
                  <VStack className="card-list card" >
                    {cards.map((card, index) => (
                      //  {card.index <= 3 && <img src={leaderboardIcons[title - 1]} alt={`Rank ${index}`} />}

                      <Card
                        key={index}
                        bgColor={"rgba(22, 75, 179, 0.6)"}
                        width={"full"}
                        // width={"90%"}
                        // id="myCard"
                      >
                        <CardHeader className="card">
                          <Flex gap={12}>
                            <Flex
                              gap="4"
                              flex={1}
                              alignItems="center"
                              // justifyContent="space-between"
                              // flexWrap="wrap"
                            >
                              <Box color={"white"}>
                                <h2>{card.title}</h2>
                              </Box>
                              <Avatar
                                name={list[index]["name"]}
                                src={`http://localhost:8000${list[index]["profile"]}`}
                              />

                              <Box color={"#FFFFFF"}>
                                <Heading size="100%">
                                  {list[index]["name"]}
                                </Heading>
                                <Text>{list[index]["username"]}</Text>
                              </Box>
                              <Box ml="auto">
                                <Heading
                                size="auto"
                                color={"#FFD53F"}
                                fontFamily="Londrina Solid"
                                >
                                {list[index]["score"]} XP
                                </Heading>
                              </Box>
                            </Flex>
                            {/* <Heading
                              size="auto"
                              color={"#FFD53F"}
                              fontFamily="Londrina Solid"
                              // alignContent="center"
                              display={"flex"}
                              justifyContent={"flex-end"}
                              alignItems={"end"}
                            >
                              {list[index]["score"]} XP
                            </Heading> */}
                          </Flex>
                        </CardHeader>
                      </Card>
                    ))}
                  </VStack>
                  {/* </Center> */}
                  <br />
                </GridItem>
              </Grid>
            </Box>
          </Flex>
        </main>
      </>
    );
  }

  return (
    <>
      <main>
        <Head>
          <title>LearderBoard</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="assets/icons/Hand_logo_yellow_1.svg" />
        </Head>

        <Flex minH={"100vh"}>
          <Box
            className="app"
            width="100%"
            bgGradient="linear(to-r, #0B51DA, #4878FF)"
          >
            <Navbar />
            <Text
              fontFamily="londrina solid"
              fontStyle="normal"
              fontWeight={400}
              fontSize={24}
              color="#FFFFFF"
              marginLeft={16}
            >
              Leaderboard
            </Text>
            <Grid
              justifySelf={"stretch"}
              marginRight="6"
              marginTop={10}
              templateColumns="repeat(2, 1fr)"
              gap={6}
            >
              <GridItem flex={1} w="100%" id="myCardsContainer">
                <Center marginLeft={10}>
                  <VStack className="card-list card">
                    {cards.map((card, index) => (
                      //  {card.index <= 3 && <img src={leaderboardIcons[title - 1]} alt={`Rank ${index}`} />}

                      <Card
                        key={index}
                        bgColor={"rgba(22, 75, 179, 0.6)"}
                        width={"2xl"}
                        id="myCard"
                      >
                        <CardHeader className="card">
                          <Flex spacing="4">
                            <Flex
                              flex="1"
                              gap="4"
                              alignItems="center"
                              flexWrap="wrap"
                            >
                              <Box color={"white"}>
                                <h2>{card.title}</h2>
                              </Box>
                              <Avatar
                                name={list[index]["name"]}
                                src={`http://localhost:8000${list[index]["profile"]}`}
                              />

                              <Box color={"#FFFFFF"}>
                                <Heading size="sm">
                                  {list[index]["name"]}
                                </Heading>
                                <Text>{list[index]["username"]}</Text>
                              </Box>
                            </Flex>
                            <Heading
                              size="sm"
                              color={"#FFD53F"}
                              fontFamily="Londrina Solid"
                              alignContent="center"
                            >
                              {list[index]["score"]} XP
                            </Heading>
                          </Flex>
                        </CardHeader>
                      </Card>
                    ))}
                  </VStack>
                </Center>
                <br />
              </GridItem>

              <GridItem display={"flex"} flexDirection={"column"} w="100%">
                <Center>
                  <Card
                    height={40}
                    bgColor={"rgba(22, 75, 179, 0.6)"}
                    width={"md"}
                  >
                    <CardHeader className="card">
                      <Flex spacing="4">
                        <Flex
                          flex="1"
                          gap="10"
                          alignItems="center"
                          flexWrap="wrap"
                        >
                          <VStack color={"white"}>
                            <Avatar
                              name={current["name"]}
                              src={`http://localhost:8000${current["profile"]}`}
                            />
                            <Box>
                              <Heading size="sm">{current["name"]}</Heading>
                              <Text>{current["username"]}</Text>
                            </Box>
                          </VStack>
                          <VStack ml={"auto"}>
                            <Text color={"white"}>#Rank</Text>
                            <Box color={"#FFD53F"} fontFamily="Londrina Solid">
                              <Heading size="md">{rank}</Heading>
                            </Box>
                          </VStack>
                          <VStack ml="auto">
                            <Text color={"white"}>#xps</Text>
                            <Box color={"#FFD53F"} fontFamily="Londrina Solid">
                              <Heading size="md">{current["score"]} XP</Heading>
                            </Box>
                          </VStack>
                        </Flex>
                      </Flex>
                    </CardHeader>
                  </Card>
                </Center>
              </GridItem>
            </Grid>
          </Box>
        </Flex>
      </main>
    </>
  );
}
