import Head from "next/head";
import { Inter } from "@next/font/google";
import {
  Box,
  Center,
  Flex,
  Heading,
  HStack,
  Link,
  VStack,
} from "@chakra-ui/layout";
import { Checkbox, color, Text } from "@chakra-ui/react";
import { Button } from "@chakra-ui/button";
import { FormControl } from "@chakra-ui/form-control";
import { Input } from "@chakra-ui/input";
const inter = Inter({ subsets: ["latin"] });
import { PinInput, PinInputField } from "@chakra-ui/react";
import { useLayoutEffect, useState } from "react";
import axios from "axios";
import { useBreakpointValue } from "@chakra-ui/react";

export default function Home() {
  const [otp, setOTP] = useState("");
  const [email, setEmail] = useState("");

  const formControlWidth = useBreakpointValue({ base: "100%", md: "md" });


  useLayoutEffect(() => {
    const email = localStorage.getItem("email");
    setEmail(email);
    console.log(email);
  }, []);
  //   const email = localStorage.getItem("email");

  const handleSubmit = async (event) => {
    event.preventDefault();

    //let responseData;
    try {
      console.log(email);
      console.log(otp);

      axios
        .post("http://127.0.0.1:8000/api/pass_reset_otp", {
          email_id: email,
          otp: otp,
        })
        .then((response) => {
          console.log("response", response.status);

          if (response.status == 200) {
            try {
              axios
                .post("http://127.0.0.1:8000/api/logout")
                .then(console.log)
                .catch(console.log);
              window.localStorage.removeItem("isLoggedIn");
              window.localStorage.removeItem("token");
              localStorage.removeItem("email");
              localStorage.removeItem("user");
              window.location.href = "/new_pass";
            } catch (error) {
              console.log(error);
              window.location.href = "/";
            }
          }
        })
        .catch(console.log);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Sign Suno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/icons/Hand_logo_yellow_1.svg" />
      </Head>
      <main style={{ height: "100vh" }}>
        <Flex height="100%">
          <Box
            flex="1"
            height="100%"
            bgImage="url('assets/images/Carousel1.svg')"
            bgPosition="center"
            bgRepeat="no-repeat"
            display={{ base: "none", lg: "block" }}
          >
            <Center>
              <VStack>
                <Text
                  color="white"
                  font="Inter"
                  fontWeight="800"
                  fontSize="28px"
                  align="center"
                  marginTop="10%"
                >
                  Accessible communication, <br /> anytime, anywhere
                </Text>

                <Text
                  color="white"
                  Font="Inter"
                  FontWeight="400"
                  FontSize="18px"
                  align="center"
                >
                  You just need stable internet connection <br />
                  and voila - engage in conversations!
                </Text>
              </VStack>
            </Center>
          </Box>
          <Box flex="1" height="100%"  display={{ base: "block", lg:"auto"}}>
            <Flex alignItems="center" justifyContent="center" minHeight="100vh">
              <Box width="100%" alignContent="center" padding="5">
                <Center  flexDirection="column">
                  <Heading marginTop="5%" fontSize="3xl" color="#0B51DA">
                    Sign
                  </Heading>
                  <Heading fontSize="3xl" color="#0B51DA">
                    सुनो
                  </Heading>
                  <Text marginTop="39px" fontSize={28} fontWeight="600" textAlign={"center"}>
                    Enter the Verification Code
                  </Text>
                  <br />
                  <Text
                    textAlign={"center"}
                    marginTop="auto"
                    fontSize={18}
                    fontWeight="700"
                    color={"#9FB1CF"}
                  >
                    We have sent an OTP to {email}
                  </Text>
                </Center>
                <br />
                <Center>
                  <VStack gap={4} width="100%">
                    <form onSubmit={handleSubmit}>
                      <VStack gap={4} width={formControlWidth}>
                        <FormControl marginTop="10px">
                          <Input
                            backgroundColor="#E2EAF8"
                            type="text"
                            placeholder="OTP"
                            value={otp}
                            onChange={(e) => setOTP(e.target.value)}
                          />
                        </FormControl>
                        <Button
                          style={{ transition: "0.2s" }}
                          backgroundColor="#0B51DA"
                          color="white"
                          type="submit"
                          width={formControlWidth}
                        >
                          Verify OTP
                        </Button>
                      </VStack>
                    </form>

                    <Text >
                      Did not get the code?
                      <Link
                        color="#0B51DA"
                        href=""
                        marginLeft="0.5"
                        _hover={{ textDecoration: "none", opacity:"0.7" }}
                      >
                        Resend Code
                      </Link>
                    </Text>
                  </VStack>
                </Center>
              </Box>
            </Flex>
          </Box>
        </Flex>
      </main>
    </>
  );
}
